name: example
description: An example of using the Settings Manager
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  settings_manager:
    path: ../packages/settings_manager
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.6+3

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  settings_gen:
    path: ../packages/settings_gen

flutter:
  uses-material-design: true
